fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(&[
                "save_settings", 
                "load_settings", 
                "greet", 
                "register_shortcut", 
                "set_auto_start", 
                "get_auto_start_status", 
                "cleanup_history", 
                "auto_paste",
                "smart_paste_to_app",
                "get_active_window_info_for_clipboard",
                "reset_database",
                "load_image_file",
                "clear_memory_cache",
                "force_memory_cleanup",
                "start_new_clipboard_watcher",
                "stop_clipboard_watcher",
                "ensure_database_compatibility",
                "get_active_window_info",
                "open_log_folder",
                "delete_all_logs"
            ]))
    ).unwrap();
}
