# Cargo配置文件 - 优化构建性能

[build]
# 使用大部分可用的CPU核心进行并行编译，但不是全部以避免系统卡死
jobs = 12
# 启用 sccache 作为 rustc 包装器
rustc-wrapper = "sccache"

[net]
# 网络重试配置
retry = 10

[registries.crates-io]
protocol = "sparse"

# Windows特定优化
[target.x86_64-pc-windows-msvc]
# 注释掉可能不存在的链接器配置
# linker = "lld-link"

[env]
# sccache 与增量编译冲突，这里关闭增量编译
CARGO_INCREMENTAL = "0"
# 启用并行前端
CARGO_BUILD_PIPELINING = "true" 


[target.x86_64-apple-darwin]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/opt/lld/bin/ld64.lld"]